spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
        username: root
        password: Toan21102002
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: none #các câu lệnh thêm cột hay xóa cột sẽ thao tác ở trên MySQL, không thao tác ở java Spring
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB

api:
    prefix: api/v1
jwt:
    expiration: 2592000 #30 days = 30*24*60*60
    secretKey: 6hVVQ8zz+xwc1vhaURMZ/VM4rw7JYFqxNaRTyUHUOxk=