spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shopapp
        username: root
        password: Toan21102002
        driver-class-name: com.mysql.cj.jdbc.Driver

    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB
